const Produits = {
    face : [
        {id : 1, title: "essence-daily-Drop-of-BEAUTY-SLEEP-AMPOULE-FACE-SERUM", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"essence-daily-Drop-of-BEAUTY-SLEEP-AMPOULE-FACE-SERUM.webp", price : 120, },
        {id : 2, title: "abcderm-cold-cream", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"abcderm-cold-cream.jpg", price : 120, },
        {id : 3, title: "absolute-hydrate-me-face-primer-parfumerie", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"absolute-hydrate-me-face-primer-parfumerie.jpg", price : 120, },
        {id : 4, title: "argiletz-argile-verte-surfine", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"argiletz-argile-verte-surfine.webp", price : 120, },
        {id : 5, title: "Bioderma-Photoderm-Max-Fluid-SPF100-40ml-nova", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Bioderma-Photoderm-Max-Fluid-SPF100-40ml-nova.webp", price : 150, },
        {id : 6, title: "cattier-creme-protection-solaire-teintee-spf-50-bio-40-ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"cattier-creme-protection-solaire-teintee-spf-50-bio-40-ml.jpg", price : 180, },
        {id : 7, title: "cerave-creme-hydratante-spf-25-visage-52-ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"cerave-creme-hydratante-spf-25-visage-52-ml.jpg", price : 280, },
        {id : 8, title: "Creme-Spf50-50ml-3282779402781-avene", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Creme-Spf50-50ml-3282779402781-avene.jpg", price : 210, },
        {id : 9, title: "Daylong-Face-Fluide-Regulateur-SPF-50_-50ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Daylong-Face-Fluide-Regulateur-SPF-50_-50ml.webp", price : 210, },
        {id : 10, title: "daylong-sensitive-face-bb-solaire-perfecteur-spf-50-fluide-teinte", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"daylong-sensitive-face-bb-solaire-perfecteur-spf-50-fluide-teinte.webp", price : 200, },
        {id : 11, title: "Daylong-Sensitive-Face-Gel-SPF50_-50ml-nova", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Daylong-Sensitive-Face-Gel-SPF50_-50ml-nova.webp", price : 200, },
        {id : 12, title: "dr-organic-masque-visage-au-cafe-125ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"dr-organic-masque-visage-au-cafe-125ml.jpg", price : 130, },
        {id : 14, title: "Ducray-dexyane-gel-nettoyant-visage-_-corps-400ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Ducray-dexyane-gel-nettoyant-visage-_-corps-400ml.webp", price : 130, },
        {id : 15, title: "Eptaderm-Creme-Visage-50-ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Eptaderm-Creme-Visage-50-ml.webp", price : 180, },
        {id : 17, title: "Exfoliac-Gel-moussant-doux-200-ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Exfoliac-Gel-moussant-doux-200-ml.jpg", price : 180, },
        {id : 18, title: "la-roche-posay-gommage-surfin-physiologique-50ml-lisse-et-assainit-en-douceur", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"la-roche-posay-gommage-surfin-physiologique-50ml-lisse-et-assainit-en-douceur.webp", price : 220, },
        {id : 19, title: "md-photowhite-correcteur-de-teint-n11-spf20-20ml", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"md-photowhite-correcteur-de-teint-n11-spf20-20ml.webp", price : 220, },
        {id : 20, title: "Neostrata-Bionic-Face-Cream-12", type:"face", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"Neostrata-Bionic-Face-Cream-12.webp", price : 170, }
    ],
    makeup : [
        {id : 1, title: "", type:"make-up", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ],
    body : [
        {id : 1, title: "", type:"body", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ],
    hair : [
        {id : 1, title: "", type:"hair", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ],
    baby : [
        {id : 1, title: "", type:"baby", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ],
    health : [
        {id : 1, title: "", type:"health", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ],
    natural : [
        {id : 1, title: "", type:"natural", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ],
    hygiene : [
        {id : 1, title: "", type:"hygiene", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ],
    solar : [
        {id : 1, title: "", type:"solar", description : "Sérum à absorption rapide sans résidu graisseux et un fini velouté qui protège la peau des dommages causés par les facteurs de stress environnementaux (radicaux libres, polluants urbains et la lumière bleue) Idéal pour tous les types de peau. Non comédogène.", src :"", price : 120, }
    ]

}